import { FormEvent, useState, useEffect } from 'react';
import type { Warehouse } from '../types';
import { Input } from '../../../components/ui/Input';
import { Select } from '../../../components/ui/Select';
import { Textarea } from '../../../components/ui/Textarea';
import { Button } from '../../../components/ui/Button';
import { SearchableSelect } from '../../../components/ui/SearchableSelect';
import { listUsers, type User } from '../api/warehouseApi';

type Props = {
  initial?: Partial<Warehouse>;
  onSubmit: (values: Omit<Warehouse, 'id' | 'created_at' | 'updated_at'>) => void;
  onCancel?: () => void;
};

export function CreateWarehouseForm({ initial, onSubmit, onCancel }: Props) {
  const [name, setName] = useState(initial?.name ?? '');
  const [address, setAddress] = useState(initial?.address ?? '');
  const [city, setCity] = useState(initial?.city ?? '');
  const [state, setState] = useState(initial?.state ?? '');
  const [pincode, setPincode] = useState(initial?.pincode ?? '');
  const [country, setCountry] = useState(initial?.country ?? '');
  const [managerId, setManagerId] = useState<string>(initial?.manager_id?.toString() ?? '');
  const [capacity, setCapacity] = useState<number | ''>(initial?.capacity ?? '');
  const [isActive, setIsActive] = useState(initial?.is_active ?? true);
  
  // Users for manager dropdown
  const [users, setUsers] = useState<User[]>([]);
  const [usersLoading, setUsersLoading] = useState(false);

  // Fetch users on component mount
  useEffect(() => {
    const fetchUsers = async () => {
      setUsersLoading(true);
      try {
        const fetchedUsers = await listUsers();
        setUsers(fetchedUsers);
      } catch (error) {
        console.error('Error fetching users:', error);
        setUsers([]);
      } finally {
        setUsersLoading(false);
      }
    };
    
    fetchUsers();
  }, []);

  // Update form fields when initial prop changes (for edit mode)
  useEffect(() => {
    if (initial) {
      setName(initial.name ?? '');
      setAddress(initial.address ?? '');
      setCity(initial.city ?? '');
      setState(initial.state ?? '');
      setPincode(initial.pincode ?? '');
      setCountry(initial.country ?? '');
      setManagerId(initial.manager_id?.toString() ?? '');
      setCapacity(initial.capacity ?? '');
      setIsActive(initial.is_active ?? true);
    } else {
      // Reset form when initial is cleared
      setName('');
      setAddress('');
      setCity('');
      setState('');
      setPincode('');
      setCountry('');
      setManagerId('');
      setCapacity('');
      setIsActive(true);
    }
  }, [initial]);
  
  // Prepare user options for SearchableSelect
  const userOptions = users.map((user) => ({
    value: user.id.toString(),
    label: `${user.id} - ${user.name}${user.email ? ` (${user.email})` : ''}${user.role ? ` [${user.role}]` : ''}`,
    id: user.id,
  }));

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    if (!name) return;

    onSubmit({
      warehouse_code: initial?.warehouse_code || '', // Will be auto-generated by backend if not provided
      name,
      address: address || undefined,
      city: city || undefined,
      state: state || undefined,
      pincode: pincode || undefined,
      country: country || undefined,
      manager_id: managerId ? Number(managerId) : undefined,
      capacity: capacity ? Number(capacity) : undefined,
      is_active: isActive,
    });
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6 text-xs">
      {/* Basic Information */}
      <div className="space-y-3">
        <h3 className="text-sm font-semibold text-slate-900">Warehouse Information</h3>
        <div className="grid gap-4 sm:grid-cols-2">
          <Input
            label="Warehouse Name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Warehouse name"
            required
          />
          {initial?.warehouse_code && (
            <div className="flex flex-col">
              <label className="text-xs font-medium text-slate-700 mb-1">Warehouse Code</label>
              <div className="text-sm text-slate-600 py-2">{initial.warehouse_code}</div>
            </div>
          )}
        </div>
        <Textarea
          label="Address"
          value={address}
          onChange={(e) => setAddress(e.target.value)}
          placeholder="Full address"
          rows={2}
        />
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <Input
            label="City"
            value={city}
            onChange={(e) => setCity(e.target.value)}
            placeholder="City"
          />
          <Input
            label="State"
            value={state}
            onChange={(e) => setState(e.target.value)}
            placeholder="State"
          />
          <Input
            label="Pincode"
            value={pincode}
            onChange={(e) => setPincode(e.target.value)}
            placeholder="Pincode"
          />
          <Input
            label="Country"
            value={country}
            onChange={(e) => setCountry(e.target.value)}
            placeholder="Country"
          />
        </div>
      </div>

      {/* Management & Capacity */}
      <div className="space-y-3">
        <h3 className="text-sm font-semibold text-slate-900">Management & Capacity</h3>
        <div className="grid gap-4 sm:grid-cols-2">
          <div className="flex flex-col">
            <label className="text-xs font-medium text-slate-700 mb-1.5">
              Manager
            </label>
            <SearchableSelect
              value={managerId}
              onChange={(value) => setManagerId(value)}
              options={userOptions}
              placeholder={usersLoading ? "Loading users..." : "Search and select manager..."}
              disabled={usersLoading}
              maxHeight="200px"
            />
            <p className="text-xs text-slate-500 mt-1">Select a user with manager role/authority</p>
          </div>
          <Input
            label="Capacity"
            type="number"
            value={capacity}
            onChange={(e) => setCapacity(e.target.value ? Number(e.target.value) : '')}
            placeholder="Storage capacity"
          />
        </div>
        <Select
          label="Status"
          value={isActive ? 'true' : 'false'}
          onChange={(e) => setIsActive(e.target.value === 'true')}
        >
          <option value="true">Active</option>
          <option value="false">Inactive</option>
        </Select>
      </div>

      {/* Form Actions */}
      <div className="mt-4 border-t border-slate-200 bg-white pt-3 flex flex-col sm:flex-row justify-end gap-2 sticky bottom-0">
        {onCancel && (
          <Button type="button" variant="ghost" size="md" onClick={onCancel} className="w-full sm:w-auto">
            Cancel
          </Button>
        )}
        <Button type="submit" variant="primary" size="md" className="w-full sm:w-auto">
          {initial?.id ? 'Update Warehouse' : 'Create Warehouse'}
        </Button>
      </div>
    </form>
  );
}
